spring:
  application:
    name: chatter-web-ui
  cloud:
    stream:
      bindings:
        output:
          destination: chat
        input:
          destination: chat

  rabbitmq:
    host: rabbitmq
